### ISSUE TITLE
uiView behavior should be documented 

### ISSUE THREAD

**Issue by stalkerg** [TehShrike/svelte-state-renderer#6]
Hello again.

I think how our render currently working with uiView not intuitively. Also, I suppose we should make able to change the query to the selector (or setup node directly).

**Comment by stalkerg** [comment]
I have strange thought - I feel we can make uiview like pure router svelte component. 
After this, we will catch events in parents components and avoid many "asr" calls.

**Comment by TehShrike** [comment]
Using different element names/selector queries in different places sounds really dangerous to me, it seems like it would get confusing without any benefit I can think of.  What's the use case/difficulty that you're thinking of?

Giving state components knowledge about their parents is a bad idea - each child state should get what it knows from the url parameters.

If you need shared global state, it should be outside of any particular component.

**Comment by stalkerg** [comment]
>What's the use case/difficulty that you're thinking of?

It's happened then I try to make nested components without nested routing. (just /hello, /counter without /app/hello, /app/counter)

>Giving state components knowledge about their parents is a bad idea - each child state should get what it knows from the url parameters.

I mean here about https://svelte.technology/guide#event-handlers :
> Events are an excellent way for nested components to communicate with their parents. 

and we can use component to switch between templates.

**Comment by stalkerg** [comment]
Also what I should do if I want only hide component (template) instead replace new?

**Comment by TehShrike** [comment]
Your different states should be communicating with each other by way of the url.  If you want to change the url parameters that determine what the parent states display, you should call [`stateRouter.go`](https://github.com/TehShrike/abstract-state-router#stateroutergostatename-stateparameters-options) (or have the user click a link built with `makePath`).

The idea is: the user should be able to refresh the page or send a link to a friend, and have exactly the same thing load as they saw when they copied the URL, because the parameters in the URL should be driving which states are displayed, and what those states are showing.

> Also what I should do if I want only hide component (template) instead replace new?

You'll probably want a child state that represents that "nothing selected" idea.  You can see an example in the state-router-example - this [no-task-selected](https://github.com/TehShrike/state-router-example/blob/master/implementations/svelte/app/topics/tasks/no-task-selected.html) state is the [default child of the `app.topics` state](https://github.com/TehShrike/state-router-example/blob/master/implementations/svelte/app/topics/topics.js#L9).

[Check out the example app](http://tehshrike.github.io/state-router-example/implementations/svelte/) to see that page in practice.

**Comment by stalkerg** [comment]
Ok, I think I can close this issue. All other question or suggestions I will ask in the other issue. 
Thanks for the help!
