### ISSUE TITLE
Reset for path with parameters and children broken

### ISSUE THREAD

**Issue by stalkerg** [TehShrike/svelte-state-renderer#7]
For example, we have two components "app" and "hello" and next path: /app/:projectid/hello .
If we change the path from /app/10/hello to /app/15/hello we will see only "app" component. 
It's happening because you destroy svelte component during reset and we have next algorithm:
destroy hello
render hello
destroy app/:projectid (with nested hello)
render app/:projectid (without nesting hello)

after that, we have only "app" component rendered.
We have two solutions. 
First:
We should destroy hello, destroy app, render app, render hello  (split destroy and render path)
Second:
Just update data params and call cb (activate).

**Comment by TehShrike** [comment]
Just updating the data on the component is an option with some other component frameworks like Ractive, which offers a `reset` method.  Svelte doesn't expose a `reset` method, so there's no way to give it new data in such a way that guarantees that any state from before won't stick around.

Because of this, the component has to be destroyed and re-created in `reset`

I have tested cases like the one you're talking about (there's a similar case in the [state-router-example](http://tehshrike.github.io/state-router-example/) when you switch back and forth between different topics) and haven't observed any bugs - can you publish a repository with an example that shows the issue you're having?  I'll help work out the issue.

**Comment by stalkerg** [comment]
>can you publish a repository with an example that shows the issue you're having?

I hope yes. I am trying to do it asap. 

>Because of this, the component has to be destroyed and re-created in reset

At least it's wrong to destroy and render begin from the end of the path because during destroy parent you destroy children component too.

**Comment by TehShrike** [comment]
I got a working reproduction at https://github.com/TehShrike/asr-svelte-renderer-reset-repro

I see what you mean now.  The child is re-created first, and when its parent is re-created right after, the creation process destroys all the children that were just reset.

**Comment by TehShrike** [comment]
I'll probably sleep on it a couple times before merging #9, but if you want to test locally with the https://github.com/TehShrike/svelte-state-renderer/tree/issue-7-fix-adding-reset branch and let me know how it works for you, that would be cool!

You should be able to point your package.json straight at `git://github.com/TehShrike/svelte-state-renderer.git` and install with npm: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by stalkerg** [comment]
I have tested your branch. The main problem is gone but you forgot about create inside a component. 
In my case, I got (set) username in "create" function and after change parameters, you reset all my changes without a call "create". But I think we shouldn't call "create" because we change only parameters from url. 

PS I know it's a bad place for getting username but we can change data for other reasons.

**Comment by stalkerg** [comment]
Probably we should add extra param for each state "type of reset": soft-reset or hard-reset.

**Comment by TehShrike** [comment]
So, right now with abstract-state-router, you should *not* rely on component lifecycle events for templates.

In order to decrease DOM work, abstract-state-router has the concept of a state ["change"ing](https://github.com/TehShrike/abstract-state-router#every-state-change-does-this-to-states), which triggers a renderer `reset` instead of a `destroy` or `create`.

This means that you can not rely on component lifecycle events.  You have to rely on the state's `activate` function, which will be called whenever the state is created, or when it changes.  To handle a state going away (whether the component is being reset or cleaned up), you need to listen to the `destroy` event on the context.

I was talking to @saibotsivad about this yesterday, and I said that I wouldn't be against adding "state lifecycle" events to components somehow, if there was a good enough reason for it.

I don't think this particular case of yours is a good reason, though - you should probably be loading the username (or doing any asynchronous loading) in the state's `resolve` function.

For work that you want to happen immediately after the state is loaded, the `activate` function is the place to add it.

If you really think this is a bad way to do things, I'm still willing to consider adding state lifecycle functions.

A longer-term plan I've considered is dropping the "change" entirely, and make every state transition involve destroying the old component and instantiating new components.  This would make the abstract-state-router code simpler, and eliminate this confusion you ran into, but would mean more DOM work and possibly some flickering when components were destroyed/recreated, depending on the component framework.

**Comment by stalkerg** [comment]
> This means that you can not rely on component lifecycle events. 

Yes, I agree and you should write about that in documentation. Also what's happens with "on" handlers? 
Should I manually remove theirs in "destroy" event? I think it reduces many benefits from svelte. 

>A longer-term plan I've considered is dropping the "change" entirely, and make every state transition involve destroying the old component and instantiating new components.

For me best variant it's when you can choose how each state can make a change. Because only I know specific each "component". 

> but would mean more DOM work and possibly some flickering when components were destroyed/recreated

It's sound bad for a "framework" like svelte. But sometimes it's the best way.

**Comment by TehShrike** [comment]
@stalkerg btw, if you want to cause create/remove events to fire on state components, you can use [asr-active-state-watcher](https://github.com/TehShrike/asr-active-state-watcher) - something like this:

```js
import makeAsrStateWatcher from 'asr-active-state-watcher'

const stateWatcher = makeAsrStateWatcher(stateRouter)
const removeAttachListener = stateWatcher.addDomApiAttachListener(domApi => {
	console.log('yargh?', domApi)
	if (domApi.onStateInit) {
		domApi.onStateInit()
	}
})
```

**Comment by TehShrike** [comment]
fyi @stalkerg, as of svelte-state-renderer@1.2.4, states are destroyed and re-created even when they are being reset.
